version: 0.2
phases:
  install:
    commands:
  pre_build:
    commands:
      - echo Installing cfg-nag
      - gem install cfn-nag
  build:
    commands:
      - echo Testing CF Template
      - aws cloudformation validate-template --template-body file://test1.yaml
      - cfn_nag_scan --input-path test1.yaml
      - aws cloudformation create-change-set --stack-name cf-test --template-body file://test1.yaml  --change-set-name cf-test-changeset --parameters ParameterKey=KeyName,ParameterValue=EC2Bill
post_build:
    commands:
      - echo "Codebuild source is:"
      - echo $CODEBUILD_SOURCE_VERSION
      - TAG=$(echo $CODEBUILD_SOURCE_VERSION | head -c 8)


artifacts:
  type: zip
  files:
    - test1.yaml
